version: "3"
services:
  web:
    build:
        context: .
        dockerfile: Dockerfile
    entrypoint: npm run start:dev
    volumes:
        - .:/usr/src/app
    ports:
        - 8000:8000
    env_file: 
        - .env
